# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170119_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_recovery_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
