# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_tvshow_first_air_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVShowEpisode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=150, null=True)),
                ('air_date', models.DateField(null=True)),
                ('season_number', models.IntegerField()),
                ('episode_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TVShowSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('season_number', models.IntegerField()),
                ('episode_count', models.IntegerField(null=True)),
                ('tv_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='api.TVShow')),
            ],
        ),
        migrations.AddField(
            model_name='tvshowepisode',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='api.TVShowSeason'),
        ),
    ]
