# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170123_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tvshowepisode',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
