# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_tvshowepisode_watchers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
