# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 15:09
from __future__ import unicode_literals

import api.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20170127_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('overview', models.TextField(null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('release_date', models.DateField(null=True)),
                ('original_language', models.CharField(blank=True, max_length=50, null=True)),
                ('poster', models.ImageField(null=True, upload_to=api.models.movie_poster_directory_path)),
                ('runtime', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MovieCastMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(blank='', max_length=150, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Person')),
            ],
        ),
        migrations.CreateModel(
            name='MovieCrewMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank='', max_length=150, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Person')),
            ],
        ),
        migrations.CreateModel(
            name='MovieSources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.CharField(max_length=50, null=True)),
                ('imdb_id', models.CharField(max_length=50, null=True)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Movie')),
            ],
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='cast',
            field=models.ManyToManyField(related_name='tv_show_cast_member', through='api.TVShowCastMember', to='api.Person'),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='crew',
            field=models.ManyToManyField(related_name='tv_show_crew_member', through='api.TVShowCrewMember', to='api.Person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(related_name='movie_cast_member', through='api.MovieCastMember', to='api.Person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='crew',
            field=models.ManyToManyField(related_name='movie_crew_member', through='api.MovieCrewMember', to='api.Person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(to='api.Genre'),
        ),
    ]
