# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_userprofile_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecastmember',
            name='character',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='moviecrewmember',
            name='job_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tvshowcastmember',
            name='character',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tvshowcrewmember',
            name='job_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
