# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20170129_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='movies_watched',
            field=models.ManyToManyField(related_name='watchers', to='api.Movie'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='movies',
            field=models.ManyToManyField(related_name='collectors', to='api.Movie'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tv_shows',
            field=models.ManyToManyField(related_name='collectors', to='api.TVShow'),
        ),
    ]
