# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20170130_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesources',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
