# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_delete_origincountry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvshowsources',
            name='freebase_id',
        ),
    ]
