# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile_password_recovery_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_recovery_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
