# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 01:09
from __future__ import unicode_literals

import api.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprofile_password_recovery_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tv_show_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=150)),
                ('overview', models.TextField(null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('in_production', models.BooleanField(default=False)),
                ('episode_count', models.IntegerField(null=True)),
                ('season_count', models.IntegerField(null=True)),
                ('backdrop', models.ImageField(null=True, upload_to=api.models.tv_show_backdrop_directory_path)),
                ('poster', models.ImageField(null=True, upload_to=api.models.tv_show_poster_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='TVShowCastMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(blank='', max_length=150, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Person')),
                ('tv_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TVShow')),
            ],
        ),
        migrations.CreateModel(
            name='TVShowCrewMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank='', max_length=150, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Person')),
                ('tv_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TVShow')),
            ],
        ),
        migrations.CreateModel(
            name='TVShowSources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.CharField(max_length=50, null=True)),
                ('imdb_id', models.CharField(max_length=50, null=True)),
                ('freebase_id', models.CharField(max_length=50, null=True)),
                ('tvdb_id', models.CharField(max_length=50, null=True)),
                ('tvrage_id', models.CharField(max_length=50, null=True)),
                ('tv_show', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.TVShow')),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.user_profile_photo_directory_path),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='cast',
            field=models.ManyToManyField(related_name='cast_member', through='api.TVShowCastMember', to='api.Person'),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='crew',
            field=models.ManyToManyField(related_name='crew_member', through='api.TVShowCrewMember', to='api.Person'),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='genres',
            field=models.ManyToManyField(to='api.Genre'),
        ),
    ]
