# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170123_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='first_air_date',
            field=models.DateField(null=True),
        ),
    ]
