# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170123_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tv_shows',
            field=models.ManyToManyField(to='api.TVShow'),
        ),
    ]
