# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userprofile_tv_shows'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshowepisode',
            name='watchers',
            field=models.ManyToManyField(to='api.UserProfile'),
        ),
    ]
