# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20170127_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='backdrop',
        ),
        migrations.AddField(
            model_name='tvshow',
            name='original_language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tvshowepisode',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='origin_country',
            field=models.ManyToManyField(to='api.OriginCountry'),
        ),
    ]
