# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20170127_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tv_shows',
            field=models.ManyToManyField(related_name='viewers', to='api.TVShow'),
        ),
    ]
