# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20170129_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='movies',
            field=models.ManyToManyField(related_name='watchers', to='api.Movie'),
        ),
    ]
