# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20170204_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvshow',
            name='origin_country',
        ),
        migrations.AddField(
            model_name='tvshow',
            name='origin_country',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
